In [2]:
!pip install pandas

Requirement already satisfied: pandas in D:\Users\prajw\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in D:\Users\prajw\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\Users\prajw\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in D:\Users\prajw\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in D:\Users\prajw\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [1]:
import pandas as pd
df=pd.read_csv('sales1_data.csv')
df.head()

         Date   Product  Sales Region
0  2023-01-01  Product3  738.0   West
1  2023-01-02  Product2  868.0  North
2  2023-01-03  Product2  554.0   West
3  2023-01-04  Product1  618.0  South
4  2023-01-05  Product3  501.0   East

In [2]:
df.isnull().sum()

Date       0
Product    0
Sales      6
Region     0
dtype: int64

In [3]:
#handling Missing Values With Mean Imputation
df['Sales'].fillna(df['Sales'].mean())

0     738.0
1     868.0
2     554.0
3     618.0
4     501.0
5     554.0
6     339.0
7     280.0
8     806.0
9     816.0
10    469.0
11    554.0
12    554.0
13    676.0
14    183.0
15    424.0
16    554.0
17    554.0
18    124.0
19    732.0
20    554.0
21    296.0
22    737.0
23    531.0
24    834.0
Name: Sales, dtype: float64

In [4]:
#Renamimhg the Column Names
df.rename(columns={'Sales':'Saless'})

          Date   Product  Saless Region
0   2023-01-01  Product3   738.0   West
1   2023-01-02  Product2   868.0  North
2   2023-01-03  Product2   554.0   West
3   2023-01-04  Product1   618.0  South
4   2023-01-05  Product3   501.0   East
5   2023-01-06  Product1     NaN   West
6   2023-01-07  Product3   339.0  South
7   2023-01-08  Product3   280.0  South
8   2023-01-09  Product2   806.0  North
9   2023-01-10  Product2   816.0  South
10  2023-01-11  Product3   469.0   West
11  2023-01-12  Product3     NaN   East
12  2023-01-13  Product3     NaN   East
13  2023-01-14  Product3   676.0   East
14  2023-01-15  Product1   183.0  South
15  2023-01-16  Product1   424.0  South
16  2023-01-17  Product1     NaN  South
17  2023-01-18  Product1     NaN  South
18  2023-01-19  Product2   124.0  North
19  2023-01-20  Product3   732.0   West
20  2023-01-21  Product2     NaN   West
21  2023-01-22  Product3   296.0   West
22  2023-01-23  Product2   737.0   West
23  2023-01-24  Product3   531.0   East
24  2023-01-25  Product2   834.0  North

In [9]:
#Data  Grouping And Aggregation
df.groupby('Sales') ['Sales'].mean()

Sales
124.0    124.0
183.0    183.0
280.0    280.0
296.0    296.0
339.0    339.0
424.0    424.0
469.0    469.0
501.0    501.0
531.0    531.0
554.0    554.0
618.0    618.0
676.0    676.0
732.0    732.0
737.0    737.0
738.0    738.0
806.0    806.0
816.0    816.0
834.0    834.0
868.0    868.0
Name: Sales, dtype: float64

In [12]:
df.groupby(['Region', 'Sales']).agg({'Sales': 'mean', 'Region': 'count'})

              Sales  Region
Region Sales
East   501.0  501.0       1
       531.0  531.0       1
       676.0  676.0       1
North  124.0  124.0       1
       806.0  806.0       1
       834.0  834.0       1
       868.0  868.0       1
South  183.0  183.0       1
       280.0  280.0       1
       339.0  339.0       1
       424.0  424.0       1
       618.0  618.0       1
       816.0  816.0       1
West   296.0  296.0       1
       469.0  469.0       1
       554.0  554.0       1
       732.0  732.0       1
       737.0  737.0       1
       738.0  738.0       1