<a href="https://colab.research.google.com/github/prajwal072/Python-basic/blob/main/panda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
#Creating a Series
data=[1,2,3,4,5,6,7,8]
#series=pd.Series(data)
#print(series)
index=['a','b','c','d','e','f','g','h']
series=pd.Series(data,index=index)
print(series)

a    1
b    2
c    3
d    4
e    5
f    6
g    7
h    8
dtype: int64

In [3]:
# Creating Series using the Dictionary
dict={
    'name':['prajwal','ashish','ashu'],
    'age':[23,45,66]

}
series=pd.Series(dict)
print(series)

name    [prajwal, ashish, ashu]
age                [23, 45, 66]
dtype: object

In [4]:
#Creating the DataFrame
data={
    'name':['prajwal','ashish','ashu'],
    'age':[23,45,66]


}
df=pd.DataFrame(data)
print(df)

      name  age
0  prajwal   23
1   ashish   45
2     ashu   66

In [5]:
df.head()#Gives First Five Elements

      name  age
0  prajwal   23
1   ashish   45
2     ashu   66

In [6]:
df.tail()  # Gives Last five elements

      name  age
0  prajwal   23
1   ashish   45
2     ashu   66

In [7]:
df['name'] #Accesing the data

0    prajwal
1     ashish
2       ashu
Name: name, dtype: object

In [8]:
df.loc[0] #accessing based on index

name    prajwal
age          23
Name: 0, dtype: object

In [9]:
df.at[2,'name']  #Accessing specific location element

'ashu'

In [17]:
df.iat[0,0]

'prajwal'

In [16]:
df

      name  age
0  prajwal   23
1   ashish   45
2     ashu   66

In [19]:
df.at[0,'name']

'prajwal'

In [20]:
#Modifying the data
df['Salary']=[1000,2000,3000]
df

      name  age  Salary
0  prajwal   23    1000
1   ashish   45    2000
2     ashu   66    3000

In [21]:
#Dropping the data
df.drop('Salary',axis=1)# Data not deleted permanently

      name  age
0  prajwal   23
1   ashish   45
2     ashu   66

In [22]:
#Dropping column Permanently
df.drop('Salary',axis=1,inplace=True)

In [ ]:
df=pd.read_csv("Sales_data")